version: "3.2"

services:

  nucleus:
    image: elementaryrobotics/nucleus
    volumes:
      - type: volume
        source: shared
        target: /shared
        volume:
          nocopy: true
    command: ./launch.sh

  voice:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: volume
        source: shared
        target: /shared
        volume:
          nocopy: true
      - "/home/dan/ER/repos/element-voice:/development"
    depends_on:
      - "nucleus"
    privileged: true

volumes:
  shared:
    driver_opts:
      type: tmpfs
      device: tmpfs
